name: publish

on:
  push:
    tags:
      - 'v*'

env:
  TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
  TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: python -m pip install --upgrade setuptools twine
    - run: python setup.py sdist
    - run: python -m twine upload dist/*
